<a href="https://colab.research.google.com/github/Devan5622/ml-from-scratch/blob/master/adjustedRsquare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

X=np.array([3,5,4,5,4,4,5,5,3,3])
Y=np.array([3,5,3,4,4,4,4,5,3,3])

def mse(actual, predicted):
    return np.mean(np.square(actual-predicted))

e1=mse(X,Y)
print(e1)
def rmse(actual, predicted):
    return np.sqrt(np.mean(np.square(actual-predicted)))
e2=rmse(X,Y)
print(e2)


def mae(actual, predicted):
    return np.mean(np.abs(actual-predicted))
e3=mae(X,Y)
print(e3)


def mape(actual, predicted):
    return np.mean(np.abs((actual - predicted) / actual)) * 100
e4=mape(X,Y)
print(e4)

def rae(actual, predicted):
    numerator = np.sum(np.abs(predicted - actual))
    denominator = np.sum(np.abs(np.mean(actual) - actual))
    return numerator / denominator
e5=rae(X,Y)
print(e5)

def r_squared(actual, predicted):
    sse = np.sum(np.square(actual-predicted))
    sst = np.sum(np.square(actual-np.mean(actual)))
    return 1 - (sse/sst)
e6=r_squared(X,Y)
print(e6)

def adj_r_squared(actual, predicted,nv): #nv is no of variables
    r_squ = r_squared(actual, predicted)
    numerator = (1 - r_squ) * len(actual)-1
    denominator = len(actual) - nv-1
    a_r_squared=1-numerator/denominator
    return a_r_squared
e7=adj_r_squared(X,Y,5)
print(e7)

def median_abs_error(actual, predicted):
    return (np.median(np.abs(actual - predicted)))
e8=median_abs_error(X,Y)
print(e8)
 
import numpy as np
X=np.array([[1, 110, 40],[1, 120, 30],[1, 100, 20],[1, 90, 0],[1, 80,10]])
Y=np.array([100,90,80,70,60])
X1=X.transpose()
print(X1)
X2=X1.dot(X)
print(X2)
X3=np.linalg.inv(X2)
print(X3)
B=X3.dot((X1.dot(Y)))
print(B)
 

0.3
0.5477225575051661
0.3
6.5
0.4166666666666667
0.5652173913043479
0.16304347826086962
0.0
[[  1   1   1   1   1]
 [110 120 100  90  80]
 [ 40  30  20   0  10]]
[[    5   500   100]
 [  500 51000 10800]
 [  100 10800  3000]]
[[ 2.02000000e+01 -2.33333333e-01  1.66666667e-01]
 [-2.33333333e-01  2.77777778e-03 -2.22222222e-03]
 [ 1.66666667e-01 -2.22222222e-03  2.77777778e-03]]
[20.   0.5  0.5]
